# Generated by Django 4.2.6 on 2024-03-20 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealthManagementApp', '0002_doctor_medical_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientappointment',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='HealthManagementApp.patient'),
        ),
    ]
