# Generated by Django 4.2.6 on 2024-04-29 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealthManagementApp', '0002_alter_doctor_patients'),
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=244, null=True)),
                ('mode', models.CharField(choices=[('In-Person', 'In-Person'), ('Online', 'Online')], default='In-Person', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='patientappointment',
            name='FollowupNote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientappointment',
            name='meeting_link',
            field=models.URLField(default='https://gmail.com/'),
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthManagementApp.doctor'),
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthManagementApp.patient'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='weekly_availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthManagementApp.weeklyavailability'),
        ),
        migrations.AlterUniqueTogether(
            name='patientappointment',
            unique_together={('doctor', 'time_slot', 'appointment_date')},
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthManagementApp.location'),
        ),
    ]
