# Generated by Django 4.2.6 on 2023-12-26 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealthManagementApp', '0003_doctor_communication_method_for_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='current_diabetes_medication',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='dietary_habits',
        ),
        migrations.AddField(
            model_name='patient',
            name='initial_medication_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='reason_for_medication',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DietaryHabits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary_habits', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietaryhabits', to='HealthManagementApp.patient')),
            ],
        ),
    ]
