# Generated by Django 4.2.6 on 2024-04-30 08:53

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('HealthManagementApp', '0003_location_patientappointment_followupnote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zoom_modal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MeetingID', models.CharField(blank=True, max_length=100, null=True)),
                ('host_id', models.CharField(blank=True, max_length=100, null=True)),
                ('host_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('topic', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.DateTimeField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('timezone', models.CharField(blank=True, max_length=100, null=True)),
                ('agenda', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, max_length=100, null=True)),
                ('start_url', models.URLField(blank=True, max_length=100, null=True)),
                ('join_url', models.URLField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='meeting_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.CharField, to='HealthManagementApp.zoom_modal'),
        ),
    ]
