# Generated by Django 4.2.6 on 2024-04-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthManagementApp', '0004_zoom_modal_alter_patientappointment_meeting_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoom_modal',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='zoom_modal',
            name='agenda',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='zoom_modal',
            name='join_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='zoom_modal',
            name='topic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
