# Generated by Django 4.2.6 on 2024-03-27 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealthManagementApp', '0004_field_form_section_fileattachment_fieldchoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='max_value',
        ),
        migrations.RemoveField(
            model_name='field',
            name='min_value',
        ),
        migrations.RemoveField(
            model_name='field',
            name='step_value',
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('password', 'Password'), ('number', 'Number'), ('email', 'Email'), ('phone', 'Phone'), ('radio', 'radio'), ('checkbox', 'Checkbox'), ('select', 'Select')], max_length=50),
        ),
        migrations.AlterField(
            model_name='form',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='HealthManagementApp.doctor'),
        ),
        migrations.AlterField(
            model_name='form',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='HealthManagementApp.patient'),
        ),
        migrations.DeleteModel(
            name='FileAttachment',
        ),
    ]
