# Generated by Django 4.2.6 on 2023-12-26 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HealthManagementApp', '0005_appointment_accepted_appointment_date_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_date',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
