# Generated by Django 4.2.6 on 2024-04-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthManagementApp', '0005_remove_zoom_modal_start_time_alter_zoom_modal_agenda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoom_modal',
            name='start_time',
            field=models.DateTimeField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zoom_modal',
            name='agenda',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zoom_modal',
            name='join_url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zoom_modal',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
