# Generated by Django 4.2.6 on 2024-03-28 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealthManagementApp', '0005_remove_field_max_value_remove_field_min_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_responses', to='HealthManagementApp.doctor')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='HealthManagementApp.form')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_responses', to='HealthManagementApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='FieldResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='HealthManagementApp.field')),
                ('form_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_responses', to='HealthManagementApp.formresponse')),
            ],
        ),
    ]
