# Generated by Django 4.2.6 on 2024-04-10 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealthManagementApp', '0006_formresponse_fieldresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMealEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.TextField()),
                ('ai_advice', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthManagementApp.patient')),
            ],
        ),
    ]
