# Generated by Django 4.2.6 on 2024-05-03 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealthManagementApp', '0007_alter_zoom_modal_join_url_alter_zoom_modal_start_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMealEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.TextField()),
                ('ai_advice', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_entries', to='HealthManagementApp.patient')),
            ],
        ),
    ]
