# Generated by Django 4.2.6 on 2024-04-10 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthManagementApp', '0007_usermealentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermealentry',
            name='patient',
        ),
    ]
