# Generated by Django 4.2.6 on 2023-12-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthManagementApp', '0008_alter_appointment_appointment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='dosage',
            new_name='dosage_info',
        ),
        migrations.AddField(
            model_name='prescription',
            name='intake_instructions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='frequency',
            field=models.IntegerField(),
        ),
    ]
