# Generated by Django 4.2.6 on 2024-04-11 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealthManagementApp', '0008_remove_usermealentry_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermealentry',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthManagementApp.patient'),
        ),
    ]
