# Generated by Django 4.2.6 on 2024-04-15 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthManagementApp', '0009_usermealentry_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermealentry',
            name='patient',
        ),
    ]
