# Generated by Django 4.2.6 on 2024-05-03 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthManagementApp', '0009_usermealentry_patient_localid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermealentry',
            name='patient_localID',
        ),
    ]
