# Generated by Django 4.2.6 on 2024-01-01 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthManagementApp', '0009_rename_dosage_prescription_dosage_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='initial_medication_details',
            new_name='current_diabetes_medication',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doctors',
        ),
    ]
