# Generated by Django 4.2.6 on 2024-01-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthManagementApp', '0010_rename_initial_medication_details_patient_current_diabetes_medication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dietary_habits',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='DietaryHabits',
        ),
    ]
