# Generated by Django 4.2.6 on 2024-01-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthManagementApp', '0012_customuser_doctor_customuser_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctors',
            field=models.ManyToManyField(related_name='patients_treated', to='HealthManagementApp.doctor'),
        ),
    ]
