# Generated by Django 4.2.6 on 2024-04-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthManagementApp', '0012_patient_email_patient_mobile_patient_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='Advices',
            field=models.ManyToManyField(blank=True, to='HealthManagementApp.advices'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='Diagnoses',
            field=models.ManyToManyField(blank=True, to='HealthManagementApp.diagnoses'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='Drug',
            field=models.ManyToManyField(blank=True, to='HealthManagementApp.drugs'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='FollowUps',
            field=models.ManyToManyField(blank=True, to='HealthManagementApp.followups'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='Histories',
            field=models.ManyToManyField(blank=True, to='HealthManagementApp.histories'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='Symptoms',
            field=models.ManyToManyField(blank=True, to='HealthManagementApp.symptoms'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='Tests',
            field=models.ManyToManyField(blank=True, to='HealthManagementApp.tests'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='Vitals',
            field=models.ManyToManyField(blank=True, to='HealthManagementApp.vitals'),
        ),
    ]
