# Generated by Django 4.2.6 on 2024-04-16 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthManagementApp', '0013_alter_prescription_advices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Mobile',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
    ]
