# Generated by Django 4.2.6 on 2024-01-09 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthManagementApp', '0014_rename_date_last_hba1c_test_and_result_patient_insurance_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='refill_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescription_approved',
            field=models.BooleanField(default=False),
        ),
    ]
