# Generated by Django 4.2.6 on 2024-01-17 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthManagementApp', '0015_prescription_refill_requested_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='communication_method_for_patient',
        ),
    ]
