# Generated by Django 4.2.6 on 2024-01-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthManagementApp', '0016_remove_doctor_communication_method_for_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='current_health_concerns',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_information',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='family_medical_history',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='health_goals',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
