# Generated by Django 4.2.6 on 2024-01-18 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealthManagementApp', '0017_patient_current_health_concerns_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='doctors',
        ),
        migrations.AddField(
            model_name='patient',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_doctor', to='HealthManagementApp.doctor'),
        ),
    ]
