# Generated by Django 4.2.6 on 2024-01-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthManagementApp', '0018_remove_patient_doctors_patient_assigned_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='assigned_doctor',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='current_health_concerns',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='emergency_contact_information',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='family_medical_history',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='health_goals',
        ),
        migrations.AddField(
            model_name='doctor',
            name='communication_method_for_patient',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='doctors',
            field=models.ManyToManyField(related_name='patients_treated', to='HealthManagementApp.doctor'),
        ),
    ]
