# Generated by Django 4.2.6 on 2024-01-25 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthManagementApp', '0019_remove_patient_assigned_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='insurance_information',
        ),
    ]
