# Generated by Django 4.2.6 on 2024-02-04 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HealthManagementApp', '0023_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
