# Generated by Django 4.2.6 on 2024-02-05 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthManagementApp', '0024_contact_submitted_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='SupportInquiry',
        ),
    ]
