# Generated by Django 4.2.6 on 2024-02-07 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthManagementApp', '0025_rename_contact_supportinquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='patients',
        ),
    ]
