# Generated by Django 4.2.6 on 2024-02-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthManagementApp', '0028_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='diabetes_management_experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='treatement_approach',
            field=models.TextField(blank=True, null=True),
        ),
    ]
