# Generated by Django 4.2.6 on 2024-02-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthManagementApp', '0029_alter_doctor_diabetes_management_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blood_sugar_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='target_blood_sugar_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
