# Generated by Django 4.2.6 on 2024-02-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthManagementApp', '0030_alter_patient_blood_sugar_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='family_medical_history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
