from rest_framework_simplejwt.views import TokenViewBase
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
from rest_framework import status
from rest_framework_simplejwt.exceptions import AuthenticationFailed, InvalidToken, TokenError